apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmarks-fish
  labels:
    app: netmarks-fish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netmarks-fish
  template:
    metadata:
      labels:
        app: netmarks-fish
    spec:
      containers:
        - name: netmarks-fish
          image: fish:0.2.9
          ports:
            - containerPort: 8080
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
#      schedulerName: netmark-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmarks-grain
  labels:
    app: netmarks-grain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netmarks-grain
  template:
    metadata:
      labels:
        app: netmarks-grain
    spec:
      containers:
        - name: netmarks-grain
          image: grain:0.2.1
          ports:
            - containerPort: 8080
#      schedulerName: netmark-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmarks-flour
  labels:
    app: netmarks-flour
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netmarks-flour
  template:
    metadata:
      labels:
        app: netmarks-flour
    spec:
      containers:
        - name: netmarks-flour
          image: flour:0.2.1
          ports:
             - containerPort: 8080
#      schedulerName: netmark-scheduler
---
