apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmarks-fish
  labels:
    app: netmarks-fish
spec:
  replicas: 20
  selector:
    matchLabels:
      app: netmarks-fish
  template:
    metadata:
      labels:
        app: netmarks-fish
    spec:
      containers:
        - name: netmarks-fish
          image: fish:0.1.5
          ports:
            - containerPort: 8080
      schedulerName: netmark-scheduler
