apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmarks-fish
  labels:
    app: netmarks-fish
spec:
  replicas: 4
  selector:
    matchLabels:
      app: netmarks-fish
  template:
    metadata:
      labels:
        app: netmarks-fish
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: netmarks-fish
          image: fish:0.4.3
          ports:
            - containerPort: 8080
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
#      schedulerName: netmark-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmarks-grain
  labels:
    app: netmarks-grain
spec:
  replicas: 4
  selector:
    matchLabels:
      app: netmarks-grain
  template:
    metadata:
      labels:
        app: netmarks-grain
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: netmarks-grain
          image: grain:0.4.3
          ports:
            - containerPort: 8080
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
#      schedulerName: netmark-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmarks-tree
  labels:
    app: netmarks-tree
spec:
  replicas: 4
  selector:
    matchLabels:
      app: netmarks-tree
  template:
    metadata:
      labels:
        app: netmarks-tree
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: netmarks-tree
          image: tree:0.4.3
          ports:
            - containerPort: 8080
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
#      schedulerName: netmark-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmarks-water
  labels:
    app: netmarks-water
spec:
  replicas: 4
  selector:
    matchLabels:
      app: netmarks-water
  template:
    metadata:
      labels:
        app: netmarks-water
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: netmarks-water
          image: water:0.4.3
          ports:
            - containerPort: 8080
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
#      schedulerName: netmark-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmarks-flour
  labels:
    app: netmarks-flour
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netmarks-flour
  template:
    metadata:
      labels:
        app: netmarks-flour
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: netmarks-flour
          image: flour:0.4.3
          ports:
             - containerPort: 8080
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
#      schedulerName: netmark-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmarks-log
  labels:
    app: netmarks-log
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netmarks-log
  template:
    metadata:
      labels:
        app: netmarks-log
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: netmarks-log
          image: log:0.4.3
          ports:
            - containerPort: 8080
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
#      schedulerName: netmark-scheduler
---
