apiVersion: v1
kind: Service
metadata:
  name: netmarks-fish
spec:
  selector:
    app: netmarks-fish
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: netmarks-flour
spec:
  selector:
    app: netmarks-flour
  ports:
    - protocol: TCP
      port: 5011
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: netmarks-grain
spec:
  selector:
    app: netmarks-grain
  ports:
    - protocol: TCP
      port: 5018
      targetPort: 8080
---