// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: pig.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PigClient is the client API for Pig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PigClient interface {
	Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type pigClient struct {
	cc grpc.ClientConnInterface
}

func NewPigClient(cc grpc.ClientConnInterface) PigClient {
	return &pigClient{cc}
}

func (c *pigClient) Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/netmarks_pig.Pig/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PigServer is the server API for Pig service.
// All implementations must embed UnimplementedPigServer
// for forward compatibility
type PigServer interface {
	Produce(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedPigServer()
}

// UnimplementedPigServer must be embedded to have forward compatible implementations.
type UnimplementedPigServer struct {
}

func (UnimplementedPigServer) Produce(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedPigServer) mustEmbedUnimplementedPigServer() {}

// UnsafePigServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PigServer will
// result in compilation errors.
type UnsafePigServer interface {
	mustEmbedUnimplementedPigServer()
}

func RegisterPigServer(s grpc.ServiceRegistrar, srv PigServer) {
	s.RegisterService(&Pig_ServiceDesc, srv)
}

func _Pig_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PigServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netmarks_pig.Pig/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PigServer).Produce(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Pig_ServiceDesc is the grpc.ServiceDesc for Pig service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pig_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmarks_pig.Pig",
	HandlerType: (*PigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _Pig_Produce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pig.proto",
}
