// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: fish.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FishClient is the client API for Fish service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FishClient interface {
	Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Single, error)
}

type fishClient struct {
	cc grpc.ClientConnInterface
}

func NewFishClient(cc grpc.ClientConnInterface) FishClient {
	return &fishClient{cc}
}

func (c *fishClient) Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Single, error) {
	out := new(Single)
	err := c.cc.Invoke(ctx, "/netmarks_fish.Fish/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FishServer is the server API for Fish service.
// All implementations must embed UnimplementedFishServer
// for forward compatibility
type FishServer interface {
	Produce(context.Context, *Request) (*Single, error)
	mustEmbedUnimplementedFishServer()
}

// UnimplementedFishServer must be embedded to have forward compatible implementations.
type UnimplementedFishServer struct {
}

func (UnimplementedFishServer) Produce(context.Context, *Request) (*Single, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedFishServer) mustEmbedUnimplementedFishServer() {}

// UnsafeFishServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FishServer will
// result in compilation errors.
type UnsafeFishServer interface {
	mustEmbedUnimplementedFishServer()
}

func RegisterFishServer(s grpc.ServiceRegistrar, srv FishServer) {
	s.RegisterService(&Fish_ServiceDesc, srv)
}

func _Fish_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FishServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netmarks_fish.Fish/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FishServer).Produce(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Fish_ServiceDesc is the grpc.ServiceDesc for Fish service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fish_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmarks_fish.Fish",
	HandlerType: (*FishServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _Fish_Produce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fish.proto",
}
