// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: iron.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IronClient is the client API for Iron service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IronClient interface {
	Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type ironClient struct {
	cc grpc.ClientConnInterface
}

func NewIronClient(cc grpc.ClientConnInterface) IronClient {
	return &ironClient{cc}
}

func (c *ironClient) Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/netmarks_iron.Iron/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IronServer is the server API for Iron service.
// All implementations must embed UnimplementedIronServer
// for forward compatibility
type IronServer interface {
	Produce(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedIronServer()
}

// UnimplementedIronServer must be embedded to have forward compatible implementations.
type UnimplementedIronServer struct {
}

func (UnimplementedIronServer) Produce(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedIronServer) mustEmbedUnimplementedIronServer() {}

// UnsafeIronServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IronServer will
// result in compilation errors.
type UnsafeIronServer interface {
	mustEmbedUnimplementedIronServer()
}

func RegisterIronServer(s grpc.ServiceRegistrar, srv IronServer) {
	s.RegisterService(&Iron_ServiceDesc, srv)
}

func _Iron_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IronServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netmarks_iron.Iron/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IronServer).Produce(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Iron_ServiceDesc is the grpc.ServiceDesc for Iron service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Iron_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmarks_iron.Iron",
	HandlerType: (*IronServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _Iron_Produce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iron.proto",
}
