// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: grain.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrainClient is the client API for Grain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrainClient interface {
	Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type grainClient struct {
	cc grpc.ClientConnInterface
}

func NewGrainClient(cc grpc.ClientConnInterface) GrainClient {
	return &grainClient{cc}
}

func (c *grainClient) Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/netmarks_grain.Grain/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrainServer is the server API for Grain service.
// All implementations must embed UnimplementedGrainServer
// for forward compatibility
type GrainServer interface {
	Produce(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGrainServer()
}

// UnimplementedGrainServer must be embedded to have forward compatible implementations.
type UnimplementedGrainServer struct {
}

func (UnimplementedGrainServer) Produce(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedGrainServer) mustEmbedUnimplementedGrainServer() {}

// UnsafeGrainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrainServer will
// result in compilation errors.
type UnsafeGrainServer interface {
	mustEmbedUnimplementedGrainServer()
}

func RegisterGrainServer(s grpc.ServiceRegistrar, srv GrainServer) {
	s.RegisterService(&Grain_ServiceDesc, srv)
}

func _Grain_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrainServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netmarks_grain.Grain/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrainServer).Produce(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Grain_ServiceDesc is the grpc.ServiceDesc for Grain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmarks_grain.Grain",
	HandlerType: (*GrainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _Grain_Produce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grain.proto",
}
