// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: ironore.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IronoreClient is the client API for Ironore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IronoreClient interface {
	Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type ironoreClient struct {
	cc grpc.ClientConnInterface
}

func NewIronoreClient(cc grpc.ClientConnInterface) IronoreClient {
	return &ironoreClient{cc}
}

func (c *ironoreClient) Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/netmarks_ironore.Ironore/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IronoreServer is the server API for Ironore service.
// All implementations must embed UnimplementedIronoreServer
// for forward compatibility
type IronoreServer interface {
	Produce(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedIronoreServer()
}

// UnimplementedIronoreServer must be embedded to have forward compatible implementations.
type UnimplementedIronoreServer struct {
}

func (UnimplementedIronoreServer) Produce(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedIronoreServer) mustEmbedUnimplementedIronoreServer() {}

// UnsafeIronoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IronoreServer will
// result in compilation errors.
type UnsafeIronoreServer interface {
	mustEmbedUnimplementedIronoreServer()
}

func RegisterIronoreServer(s grpc.ServiceRegistrar, srv IronoreServer) {
	s.RegisterService(&Ironore_ServiceDesc, srv)
}

func _Ironore_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IronoreServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netmarks_ironore.Ironore/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IronoreServer).Produce(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Ironore_ServiceDesc is the grpc.ServiceDesc for Ironore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ironore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmarks_ironore.Ironore",
	HandlerType: (*IronoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _Ironore_Produce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ironore.proto",
}
