// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: bread.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BreadClient is the client API for Bread service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BreadClient interface {
	Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type breadClient struct {
	cc grpc.ClientConnInterface
}

func NewBreadClient(cc grpc.ClientConnInterface) BreadClient {
	return &breadClient{cc}
}

func (c *breadClient) Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/netmarks_bread.Bread/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BreadServer is the server API for Bread service.
// All implementations must embed UnimplementedBreadServer
// for forward compatibility
type BreadServer interface {
	Produce(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedBreadServer()
}

// UnimplementedBreadServer must be embedded to have forward compatible implementations.
type UnimplementedBreadServer struct {
}

func (UnimplementedBreadServer) Produce(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedBreadServer) mustEmbedUnimplementedBreadServer() {}

// UnsafeBreadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BreadServer will
// result in compilation errors.
type UnsafeBreadServer interface {
	mustEmbedUnimplementedBreadServer()
}

func RegisterBreadServer(s grpc.ServiceRegistrar, srv BreadServer) {
	s.RegisterService(&Bread_ServiceDesc, srv)
}

func _Bread_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreadServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netmarks_bread.Bread/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreadServer).Produce(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Bread_ServiceDesc is the grpc.ServiceDesc for Bread service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bread_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmarks_bread.Bread",
	HandlerType: (*BreadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _Bread_Produce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bread.proto",
}
