apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: verbosity-echo-release
  namespace: '866102919331'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: 46f1d850-3742-4e0e-8c3a-02143b7d18f4
    gcb-trigger-region: global
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: verbosity.io.main@gmail.com
    serving.knative.dev/lastModifier: verbosity.io.main@gmail.com
    run.googleapis.com/operation-id: ea35b399-37f9-474d-9958-c70d6f970fd8
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/maxScale: '2'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 866102919331-compute@developer.gserviceaccount.com
      containers:
        - image: gcr.io/cloudrun/placeholder
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: KEY
              value: VALUE
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
  traffic:
    - percent: 100
      latestRevision: true
status:
  observedGeneration: 2
  conditions:
    - type: Ready
      status: 'True'
      lastTransitionTime: '2023-09-18T18:44:34.647557Z'
    - type: ConfigurationsReady
      status: 'True'
      lastTransitionTime: '2023-09-18T18:42:55.102780Z'
    - type: RoutesReady
      status: 'True'
      lastTransitionTime: '2023-09-18T18:44:34.647557Z'
  latestReadyRevisionName: verbosity-echo-release-00001-rhj
  latestCreatedRevisionName: verbosity-echo-release-00001-rhj
  traffic:
    - revisionName: verbosity-echo-release-00001-rhj
      percent: 100
      latestRevision: true
  url: https://verbosity-echo-release-ikfts3ttaa-uc.a.run.app
  address:
    url: https://verbosity-echo-release-ikfts3ttaa-uc.a.run.app
