// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: gold.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoldClient is the client API for Gold service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoldClient interface {
	Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type goldClient struct {
	cc grpc.ClientConnInterface
}

func NewGoldClient(cc grpc.ClientConnInterface) GoldClient {
	return &goldClient{cc}
}

func (c *goldClient) Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/netmarks_gold.Gold/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoldServer is the server API for Gold service.
// All implementations must embed UnimplementedGoldServer
// for forward compatibility
type GoldServer interface {
	Produce(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGoldServer()
}

// UnimplementedGoldServer must be embedded to have forward compatible implementations.
type UnimplementedGoldServer struct {
}

func (UnimplementedGoldServer) Produce(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedGoldServer) mustEmbedUnimplementedGoldServer() {}

// UnsafeGoldServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoldServer will
// result in compilation errors.
type UnsafeGoldServer interface {
	mustEmbedUnimplementedGoldServer()
}

func RegisterGoldServer(s grpc.ServiceRegistrar, srv GoldServer) {
	s.RegisterService(&Gold_ServiceDesc, srv)
}

func _Gold_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netmarks_gold.Gold/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldServer).Produce(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Gold_ServiceDesc is the grpc.ServiceDesc for Gold service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gold_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmarks_gold.Gold",
	HandlerType: (*GoldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _Gold_Produce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gold.proto",
}
