// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: beer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BeerClient is the client API for Beer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BeerClient interface {
	Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type beerClient struct {
	cc grpc.ClientConnInterface
}

func NewBeerClient(cc grpc.ClientConnInterface) BeerClient {
	return &beerClient{cc}
}

func (c *beerClient) Produce(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/netmarks_beer.Beer/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeerServer is the server API for Beer service.
// All implementations must embed UnimplementedBeerServer
// for forward compatibility
type BeerServer interface {
	Produce(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedBeerServer()
}

// UnimplementedBeerServer must be embedded to have forward compatible implementations.
type UnimplementedBeerServer struct {
}

func (UnimplementedBeerServer) Produce(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedBeerServer) mustEmbedUnimplementedBeerServer() {}

// UnsafeBeerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeerServer will
// result in compilation errors.
type UnsafeBeerServer interface {
	mustEmbedUnimplementedBeerServer()
}

func RegisterBeerServer(s grpc.ServiceRegistrar, srv BeerServer) {
	s.RegisterService(&Beer_ServiceDesc, srv)
}

func _Beer_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeerServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/netmarks_beer.Beer/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeerServer).Produce(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Beer_ServiceDesc is the grpc.ServiceDesc for Beer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Beer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmarks_beer.Beer",
	HandlerType: (*BeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _Beer_Produce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "beer.proto",
}
